spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 829586954512-2tftm9ddb65l7b83rpsmto0etdl5hmkl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            clientId: 9GbbbeEvBnaJyRrbIuc2
            clientSecret: n46SoNYj3U
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.