spring:
  jpa:
    hibernate:
      ddl-auto: none
    datasource:
      url: jdbc:mariadb://oldbook.cs6cgjrsdwba.ap-northeast-2.rds.amazonaws.com:3306/oldbook_db
      username: minyuk
      password: alsgur4316
      driver-class-name: org.mariadb.jdbc.Driver