server:
  servlet:
    encoding:
      charset: utf-8

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mariadb://oldbook-db.cs6cgjrsdwba.ap-northeast-2.rds.amazonaws.com:3306/oldbook-db
    driver-class-name: org.mariadb.jdbc.Driver
    username: minyuk
    password: alsgur4316

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    '[org.springframework.boot.web]': INFO