server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/old_book?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: alsgur4316@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true

  output:
    ansi:
      enabled: always

file:
  dir: /Users/kangminhyeok/Desktop/project/book/src/old-book-store/src/main/resources/static/uploadFile

#logging:
#  level:
#    '[org.springframework.web]': DEBUG
#    '[org.hibernate]': DEBUG