server:
  servlet:
    encoding:
      charset: utf-8

spring:
  main:
    allow-circular-references: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  session:
    store-type: jdbc

logging:
  level:
    '[org.springframework.boot.web]': INFO

file:
  dir: /Users/kangminhyeok/Desktop/project/book/src/old-book-store/src/main/resources/static/uploadFile